repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/hakancelik96/unimport
    rev: 1.2.1
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: ".ipynb"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--skip=*.il", "-L TE,TE/TM,te,ba,FPR,fpr_spacing,ro,donot,grat,synopsys"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [--exit-zero]
        # ignore all tests, not just tests data
        exclude: ^tests/

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.0
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      # args: [ --fix ]
    # Run the linter and sort imports
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --select, I, --fix ]
    # # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

# To run pre-commit manually use: `pre-commit run --all-files`
